### ISSUE TITLE
Import doesn't work as shown in the readme

### ISSUE THREAD

**Issue by leMaik** [PlatziDev/socket.io-react#2]
When using Webpack+Babel, due to the way `SocketProvider` and `socketConnect` are re-exported [here](https://github.com/PlatziDev/socket.io-react/blob/bf5cecd3744d1b68b6d171bda90503fc216ec390/lib/index.js#L4), they can't be imported with `import { SocketProvider, socketConnect } from 'socket.io-react'` but only by importing the `default` export and then de-structuring that object.

Thank you for the great component! :+1:

**Comment by sergiodxa** [comment]
Merged the fix #3
