### ISSUE TITLE
`socket.io-client` disappears while trying to run

### ISSUE THREAD

**Issue by shisaq** [PlatziDev/socket.io-react#4]
Hi,

I followed your instruction, but failed to config, because I cannot `import io from 'socket.io-client';` while going for `SocketProvider(socket?)`. I was afraid `socket.io-react` didn't exist in `node_modules` folder?

**Comment by shisaq** [comment]
Ah, I found it. `socket.io-client` is another `npm` module. I think maybe you can add the [dependency](https://www.npmjs.com/package/socket.io-client) into your readme.

**Comment by sergiodxa** [comment]
It's a `peerDependency` (you should get a warning in the console after installing this module), that allow you to use the version of socket.io-client you want (or event another WebSocket client, this can work with any WebSocket implementation).
